---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Edit network information
- type: directory
  path: src/_data/information
  label: Network Information
  create: all
  match: "*.json"
  new_doc_ext: json
- type: heading
  label: Edit Resources, Blog, Events, News
- type: directory
  path: src/content/news
  label: News
  create: documents
  match: "**/*.md"
  templates:
  - PAGE-news
- type: directory
  path: src/content/resources
  label: Resources
  create: all
  match: "**/*.md"
  templates:
  - PAGE-resources
- type: directory
  path: src/content/events
  label: Events
  create: all
  match: "**/*.md"
  templates:
  - CONTENT-events
- type: heading
  label: Edit Page headings
- type: document
  path: src/_data/pages/homepage.json
  label: Homepage content
- type: directory
  path: src/_data/pages/about
  label: About page content
  create: documents
  match: "**/*"
- type: directory
  path: src/_data/pages/what
  label: What we do content
  create: documents
  match: "**/*"
- type: directory
  path: src/_data/pages/sdgs
  label: Local SDGs content
  create: documents
  match: "**/*"
- type: directory
  path: src/_data/pages/involved
  label: Get Involved content
  create: documents
  match: "**/*"
- type: document
  path: src/_data/pages/searchPage.json
  label: Search page
- type: heading
  label: Website structure
- type: document
  path: src/_data/wdefaults/navigation.json
  label: Navigation Bar
- type: document
  path: src/_data/wdefaults/websitecolours.json
  label: Edit Colour Theme
- type: document
  path: src/_data/wdefaults/socialMediaIcons.json
  label: Edit Social Media Icons
upload_dir: src/assets/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
